### ISSUE TITLE
Deep search is broken

### ISSUE THREAD

**Issue by sgdavis1** [titarenko/fast-exif#1]
I have a few files that were failing to find exif data even though I knew it existed. So I took a closer look at the code, and Should line 40 be adjusted from:
`return isDeepSearch ? searchExif(fd, buffer, fileOffset + length) : null;`

To this:
`return isDeepSearch ? searchExif(fd, buffer, fileOffset + length, true) : null;`

At least seemed to fix my problem.

**Comment by titarenko** [comment]
Could you please make pull request? I'll then merge it. Thanks!
