### ISSUE TITLE
Extract some exif tag

### ISSUE THREAD

**Issue by lcarado** [titarenko/fast-exif#3]
I have an simple question: can I extract a particolar exit tag (example exif.DateTimeOriginal) and save it in a variable?
I don't understand which kind of object is returned from "exif.read('my.jpg')"
The ideal use for me is to add some exif tag proprieties to 'my.jpg' object.
Thanks

**Comment by titarenko** [comment]
Hi!

> I have an simple question: can I extract a particolar exit tag (example exif.DateTimeOriginal) and save it in a variable?

Sure, you can, for example: `const myVar = await exif.read('my.jpg').then(result => result.exif.DateTimeOriginal)`.

> I don't understand which kind of object is returned from "exif.read('my.jpg')"

The structure of `read` function result is best described [here](https://github.com/devongovett/exif-reader#usage) (fast-exif uses exif-reader package).

> The ideal use for me is to add some exif tag proprieties to 'my.jpg' object.

Unfortunately, this is not possible with this package. It supports only reading exif information from file.
