### ISSUE TITLE
Is it possible to update your plugin for ionic 4 ?

### ISSUE THREAD

**Issue by jbdioli** [titarenko/fast-exif#5]

**Comment by hassanxali** [comment]
YES PLEASE!

**Comment by hassanxali** [comment]
@jbdioli have u found a solution yet?

**Comment by jbdioli** [comment]
@hassanxali I found an other plugin https://github.com/mattiasw/ExifReader
And it works well

**Comment by hassanxali** [comment]
@jbdioli Just installed the plugin but i'm confused in how to pass the image as "buffer". All i have is the path of the image, how do u get the image buffer?

**Comment by jbdioli** [comment]
@hassanxali 

You need to convert the image first to a ArrayBuffer

download the code and I hope it will help you to understand :)

https://github.com/jbdioli/ExifReader.git

**Comment by mattiasw** [comment]
@hassanxali The ExifReader README links to an examples folder that shows how to load a file using the path of the image: https://github.com/mattiasw/ExifReader#loading-tags

**Comment by titarenko** [comment]
Hi @jbdioli 

sorry for late response
actually I'm not sure I got the details of this issue

fast-exif is just a js library targeted to be run in node.js env, it was not designed as a plugin of Ionic framework

if that's still the question 

- what exactly do you want to use fast-exif for? 
- and what do you need to get updated to be able to achieve your goal?

thank you for the interest to fast-exif!

**Comment by titarenko** [comment]
closing as stale
please reopen if it's still actual
